spring.application.name=tienda
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/angels_demons?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=santiago
spring.datasource.password=4542984Yady*

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false